@startuml Smart Lightbulb


hide footbox
autonumber
 

' More examples https://www.planttext.com/ 
'Here is a gallery of the available themes: : https://the-lum.github.io/puml-themes-gallery/
'!theme cerulean

' use 'plain' theme for oneM2M standards submissions and 
skinparam BackgroundColor transparent
!theme plain


    participant "mcu" as lb <<light bulb>>

    participant "CSE" as cse <<IoT Platform>>
    participant "Client Web Service" as app <<web page>>




lb -> cse : register device
lb -> cse : send state

app -> cse : register app
app -> cse : get state

loop steady state

lb -> cse: get commands
lb -> cse: send state

app -> cse: get state 
app -> cse: send commands 

end


@enduml